---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
     - recipe[opsmatic::agent]
      
    attributes:
      {
        "opsmatic": {
          "integration_token": "<YOUR INTEGRATION TOKEN>",
          "file-monitor-list": ['/etc/nginx/nginx.conf','/etc/ssh/sshd_config','/etc/rsyslog.conf','/etc/hosts','/etc/passwd']
        }
      }
